import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import { Footer } from "@/components/footer";
import { Banner } from "@/components/navigation/banner";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Machulec – Das Profiteam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="de">
      <body
        className={cn("font-light antialiased", geistSans.variable, geistMono.variable)}
      >
        <Banner />
        <div className="px-4 sm:px-10 md:px-28">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
